/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppAnalyzeRouteImport } from './routes/app.analyze'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/results': typeof AppResultsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/results': typeof AppResultsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/results': typeof AppResultsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analyze'
    | '/app/history'
    | '/app/results'
    | '/app/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/analyze'
    | '/app/history'
    | '/app/results'
    | '/app/upload'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analyze'
    | '/app/history'
    | '/app/results'
    | '/app/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyze': {
      id: '/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppResultsRoute: typeof AppResultsRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppResultsRoute: AppResultsRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
